### ISSUE TITLE
account name bad parsing

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-extractor-snowflake#19]
The extractor expects DB `host` param as third-level domain in format `xxx.yyyy.zz`.
But snoflake also provides fourt level domain `yyy.xxx.yyyy.zz`.

So extractor fails on snowsql connect, because accoun name is parsed badly.
https://github.com/keboola/db-extractor-snowflake/blob/master/src/Keboola/DbExtractor/Extractor/Snowflake.php#L235

**Comment by Halama** [comment]
tohle je fixnutý
