### ISSUE TITLE
Downloading error

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-snowflake#37]
https://connection.keboola.com/admin/utils/logs?file=2018/01/25/03/2018-01-25-03-10-39-5a693c9f58a62-exception

thrown here: https://github.com/keboola/db-extractor-snowflake/blob/9c5c91c35cb63aa4d4098719a49c76f378cf61c8/src/Keboola/DbExtractor/Extractor/Snowflake.php#L96

Maybe related to `dst_file_size` error: https://connection.keboola.com/admin/utils/logs?file=2018/01/25/05/2018-01-25-05-28-28-5a695cece5250-exception

**Comment by pivnicek** [comment]
Fisa hlásí error z loadu do Snowflake, kterej není náš. Jde o tenhle job: https://connection.keboola.com/admin/projects/4191/jobs/349454445?q=

![image](https://user-images.githubusercontent.com/569139/35406013-0cc95cac-0208-11e8-9acd-4ccc7e95bdac.png)

**Comment by Halama** [comment]
how did you identified that line https://github.com/keboola/db-extractor-snowflake/blob/9c5c91c35cb63aa4d4098719a49c76f378cf61c8/src/Keboola/DbExtractor/Extractor/Snowflake.php#L96 ?

**Comment by Halama** [comment]
I think it was thrown here https://github.com/keboola/db-extractor-snowflake/blob/fdff3ce906f0be7e8715d1a9b68a560b6a5f65de/src/Keboola/DbExtractor/Extractor/Snowflake.php#L214

**Comment by pivnicek** [comment]
There were 2 errors.  The first https://connection.keboola.com/admin/utils/logs?file=2018/01/25/03/2018-01-25-03-10-39-5a693c9f58a62-exception

Was I believe thrown on 96:
![image](https://user-images.githubusercontent.com/569139/35408896-f2781f10-0210-11e8-8054-c4ed81a66d87.png)

The second https://connection.keboola.com/admin/utils/logs?file=2018/01/25/05/2018-01-25-05-28-28-5a695cece5250-exception

Was thrown on your line.

I still don't know if/how they're related

**Comment by Halama** [comment]
And the problem could be here https://github.com/keboola/db-extractor-snowflake/blob/fdff3ce906f0be7e8715d1a9b68a560b6a5f65de/src/Keboola/DbExtractor/Extractor/Snowflake.php#L188
I can't find that `GET @%s/%s file://%s;` anywhere documented. But we can simulate it and check which SNFLK commands are executed from snowsql.

**Comment by Halama** [comment]
oh, yes these are two different jobs with diferrent errors:(

**Comment by Halama** [comment]
Jenom si sem poznamenám jak vypadá ten výstup toho snowsql:
```
1 Row(s) produced. Time Elapsed: 0.508s
part_0_0_0.csv.gz(0.00MB): [##########] 100.00% Done (2.178s, 0.00MB/s).
+-------------------+------+------------+---------+
| file              | size | status     | message |
|-------------------+------+------------+---------|
| part_0_0_0.csv.gz |   88 | DOWNLOADED |         |
+-------------------+------+------------+---------+
1 Row(s) produced. Time Elapsed: 7.411s
Goodbye!

```

**Comment by Halama** [comment]
Jenom si poznamenám:
```

            COPY INTO @~/in_c-keboola-ex-db-snowflake-349891662_large-31g/part
            FROM (SELECT * FROM "snowflake_extractor"."LARGE_31G")

            FILE_FORMAT = (TYPE=CSV FIELD_DELIMITER = ',' FIELD_OPTIONALLY_ENCLOSED_BY = '\"' ESCAPE_UNENCLOSED_FIELD = '\\' COMPRESSION = 'GZIP' NULL_IF=())
            HEADER = false
            MAX_FILE_SIZE=50000000
            OVERWRITE = TRUE
            ;
            
```

**Comment by Halama** [comment]
```
root@4d79a90fed1f:/tmp/ex-snowflake/run-5a70864219bea5.87404476# cat snowsql.config 

[options]
exit_on_error = true

[connections.downloader]
accountname = "kebooladev"
username = "martin_snflk_extractor"
password = "XXX"
dbname = "martin_snflk_extractor"
schemaname = "snowflake_extractor"
warehousename = "DEV"

root@4d79a90fed1f:/tmp/ex-snowflake/run-5a70864219bea5.87404476# cat 5a708e99594ac-snowsql.sql 
USE DATABASE "martin_snflk_extractor";
USE SCHEMA "snowflake_extractor";
USE WAREHOUSE "DEV";
GET @~/in_c-keboola-ex-db-snowflake-349891662_large-31g file:///data/out/tables/in_c-keboola-ex-db-snowflake-349891662_large-31g.csv.gz
```

**Comment by Halama** [comment]
Zatím to stahuje na disk https://connection.keboola.com/admin/projects/4088/jobs/351199885
V kontejneru se místo neplní vše leze do mountnutého `/data/out/tables/in_c-keboola-ex-db-snowflake-349891662_large-31g.csv.gz` kde to postupně stahuje jednotlivé slices:
![image](https://user-images.githubusercontent.com/903531/35575038-a8b76722-05db-11e8-98a6-9062c2f8223e.png)

**Comment by Halama** [comment]
Staženo 736 souborů a 35GB a zatím jede dál, podle snflk by to mělo mít 70GB po unloadu do stage.
https://connection.keboola.com/admin/projects/4088/extractors/keboola.ex-db-snowflake/349891662

**Comment by Halama** [comment]
ted uz to ma 1263 souboru takze to stejne neprojde do SAPI ale uvidim jestli alespon ten kontejner dojede bez chyby.

**Comment by Halama** [comment]
Takže to skončilo po přesně stejné době chybou jako předtím: `Cannot download file: part_0_0_103.csv.gz Status: ERROR Size: -1 Message: An error occurred (400) when calling the HeadObject operation: Bad Request` Ale na jiném slicu.

Zkusím updatnout SnowSQL a jestli to nezabere tak Won't fix dokud nebude ten extractor updatnuty na přímý output mapping do Keboola S3.

**Comment by Halama** [comment]
Nasazena verze s novými drivery a job spuštěn https://connection.keboola.com/admin/projects/4088/jobs/351425447

**Comment by Halama** [comment]
Vypadá to že to vše postahovalo, 1559 souborů 73GB . Kontejner ale pořád běží a moc nevím co teda dělá.

**Comment by Halama** [comment]
OMG, ono to ted přeppisuje 1600x ten manifest pořád dokola https://github.com/keboola/db-extractor-snowflake/blob/12b186207c4ac011a65af6ab8260dedf1f2001b1/src/Keboola/DbExtractor/Extractor/Snowflake.php#L214

**Comment by Halama** [comment]
Jinak to teda znamená že už to prošlo kritickým místem.

**Comment by Halama** [comment]
Tak už to validně spadlo na `Cannot upload file 'in_c-keboola-ex-db-snowflake-349891662_large-31g.csv.gz' to table 'in.c-keboola-ex-db-snowflake-349891662.large-31g' in Storage API: Load error: odbc_prepare(): SQL error: The number of files exceeds the 1,000 limit., SQL state 22000 in SQLPrepare`

**Comment by pivnicek** [comment]
`The number of files exceeds the 1,000 limit` huh. not sure which way to approach that, could be an issue for https://github.com/keboola/php-db-import maybe?

**Comment by Halama** [comment]
It is known issue I was excpected this error. We'll solve it later.

**Comment by Halama** [comment]
It look like issue is not created, I'll create it.

**Comment by Halama** [comment]
https://github.com/keboola/php-db-import/issues/39

**Comment by Halama** [comment]
tohle zaviram, vypada to ze update snowsql zabral
