### ISSUE TITLE
Table manifest is overwritten for each slice

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-snowflake#43]
https://github.com/keboola/db-extractor-snowflake/blob/12b186207c4ac011a65af6ab8260dedf1f2001b1/src/Keboola/DbExtractor/Extractor/Snowflake.php#L214

**Comment by Halama** [comment]
That iterated value `$csvFile` is even not used in the loop. So it is just a slow down loop :)

**Comment by pivnicek** [comment]
Except for $bytes, which would make the final over-write correct :p omg

**Comment by Halama** [comment]
yes but these `$bytes` are not written to manifest so i didn't mention it.

**Comment by Halama** [comment]
I'll fix it and refactor that shitty method.

**Comment by pivnicek** [comment]
smh, it's all crazy

**Comment by Halama** [comment]
And it is super slow when it is iterating 1600 files :)
