### ISSUE TITLE
Retry on statement timeout

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-snowflake#45]
If a statement times out it throws an application error,

![image](https://user-images.githubusercontent.com/569139/35795434-72bbbcae-0a59-11e8-9375-e6ae6115361a.png)

Should be retrying this

**Comment by kacurez** [comment]
happened again https://keboola.slack.com/archives/C09U3R1J4/p1549416186011800

**Comment by pivnicek** [comment]
Moving this to #79 .
