### ISSUE TITLE
rtrim semicolon from SQL

### ISSUE THREAD

**Issue by ErikZigo** [keboola/db-extractor-snowflake#5]
- [ ] describe extraction flow in readme
- [x] rtrim ";" from SQL

**Comment by Halama** [comment]
wtf

**Comment by ErikZigo** [comment]
ty mas same wtf

**Comment by ErikZigo** [comment]
V EX se zadava query. Ta se vezme a prida do COPY INTO query.

**Comment by ErikZigo** [comment]
Takze se musi ta query z konfigurace vzit a orezat z ni strednik. Jinak to failne
