### ISSUE TITLE
Broken build: Unable to locate package unixODBC-dev

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-snowflake#64]

**Comment by Halama** [comment]
you can copy it from [dwhm](https://github.com/keboola/app-snowflake-dwh-manager/blob/master/Dockerfile)

**Comment by pivnicek** [comment]
great, thanks!

**Comment by pivnicek** [comment]
changing ti to lower-case and adding `unixodbc` was enough to fix the build for now, I'll make a separate issue to update it to follow the dwhm way (getting driver from aws etc...)

**Comment by pivnicek** [comment]
I also see that this is duplicate of https://github.com/keboola/db-extractor-snowflake/issues/59
