### ISSUE TITLE
Failed to get tables: 'Undefined index: INFORMATION_SCHEMA.COLUMNS

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-snowflake#72]
I am trying to download account usage https://connection.keboola.com/admin/projects/258/extractors/keboola.ex-db-snowflake/461070099

https://connection.keboola.com/admin/utils/logs?file=2018/11/07/10/2018-11-07-10-26-10-5be2afb2bbfe6-exception

In the UI it works:
https://connection.keboola.com/admin/projects/258/extractors/keboola.ex-db-snowflake/461070099

**Comment by Halama** [comment]
I am trying to run it locally and debug it.

**Comment by pivnicek** [comment]
Strange.

**Comment by Halama** [comment]
also it is strange that it doesn't throw application error. This one looks like error message from PHP.

**Comment by pivnicek** [comment]
yes, this https://github.com/keboola/db-extractor-common/blob/master/src/Keboola/DbExtractor/Application.php#L205 should probably be changed to application exception.

**Comment by Halama** [comment]
final i was able to run it locally :)

**Comment by pivnicek** [comment]
It won't solve this issue, but I want to get this merged https://github.com/keboola/db-extractor-snowflake/pull/71

**Comment by Halama** [comment]
So the error is throw on this line https://github.com/keboola/db-extractor-snowflake/blob/e0c02f3091d8627bdc63d39bb98cf1631fb9997c/src/Keboola/DbExtractor/Extractor/Snowflake.php#L444

And I think it is because there aren't tables filtered also by schema name 
https://github.com/keboola/db-extractor-snowflake/blob/e0c02f3091d8627bdc63d39bb98cf1631fb9997c/src/Keboola/DbExtractor/Extractor/Snowflake.php#L415

**Comment by pivnicek** [comment]
Got it.  Thanks

**Comment by pivnicek** [comment]
I'm going to add the fix to a PR on top of https://github.com/keboola/db-extractor-snowflake/pull/71 since the current master build isn't even working.
