### ISSUE TITLE
Fail parsing files

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-snowflake#81]
`CRITICAL: Exception:Cannot download file: part_0_0_0.csv.gz Status: NOT_FOUND_FILE Size: -1 Message: float() argument must be a string or a number, not 'NoneType'`

thrown on https://github.com/keboola/db-extractor-snowflake/blob/master/src/Keboola/DbExtractor/Extractor/Snowflake.php#L537

Not sure how to reproduce this
https://keboola.slack.com/archives/C09U3R1J4/p1552307471010900

**Comment by pivnicek** [comment]
dalsi: https://keboola.slack.com/archives/C09U3R1J4/p1552517811023800

**Comment by ErikZigo** [comment]
Zacla jsem to zkoumat vcera kdyz jsem mel chyby.

Tahle chyba nastala kdyz se pres SnowSQL stahuje unloadnuta tabulka z USER stage.

**Comment by pivnicek** [comment]
aha, nj.  tak to nebude problem az budeme mit https://github.com/keboola/db-extractor-snowflake/issues/1 hotovo

**Comment by ErikZigo** [comment]
Jedna z konfiguraci na ktery to failovalo byla z guide mode projektu. Koukal jsem ze tam se pro vsechny pouzivaji stejny credentials do DB.

Napadlo me ze by to mohlo souviset s tim kdy by se pod stejnym userem delal v jednu chvili export z vice tabulek naraz. Ze by se v user stagi data vymazaly a pak to skoncilo touhle chybou.

Tim to ale nebude. Protoze ty konfigurace maji nastavenu `outputTable` unikatni.
Takze ty unloadnuty tabulky tam kazda lezi s jinym prefixem a vubec to na sebe nema vliv. Data se nijak neprepisou.

**Comment by ErikZigo** [comment]
Kdyz stahuju data z user stage pres SnowSQL tak dostanu vysledek:

```
part_0_0_0.csv.gz(0.01MB): [##########] 100.00% Done (0.460s, 0.02MB/s).        
+-------------------+------+------------+---------+
| file              | size | status     | message |
|-------------------+------+------------+---------|
| part_0_0_0.csv.gz | 8414 | DOWNLOADED |         |
+-------------------+------+------------+---------+
1 Row(s) produced. Time Elapsed: 3.063s
```

Zkusil jsem schvalne vymazat soubory ze stagingu a spustit SnowSQL znovu:

```
+------+------+--------+---------+                                              
| file | size | status | message |
|------+------+--------+---------|
+------+------+--------+---------+
0 Row(s) produced. Time Elapsed: 1.493s
```
Tzn pokud soubor neexistuje ve snowflaku, tak to zadnou chybou neskonci.

**Comment by ErikZigo** [comment]
Ta chyba ale znamena ze proces snowsql skoncil chybou a vypsalo to neco takoveho:

```
+-------------------+------+----------------+-------------------------------------------------+
| file              | size |     status     |                      message                    |
|-------------------+------+----------------+-------------------------------------------------|
| part_0_0_0.csv.gz |  -1  | NOT_FOUND_FILE | float() argument must be a string or a numb ... |
+-------------------+------+----------------+-------------------------------------------------+
```

**Comment by ErikZigo** [comment]
Chyba se v poslednich den vyskytla jen u dvou konfiguraci. U jedne opakovane. Ale to je diky frekvenci spusteni.

**Comment by ErikZigo** [comment]
Zatim ne napadaji dve moznosti:
- zkusit upgradovat SnowSQL na novejsi verzi
- udelat retry na SnowSQL

**Comment by ErikZigo** [comment]
Pripadne prostouchnout vyhozeni snowsql a nahrazeni direct uploadem to S3
Koukam ze to issue je stary dva roky 👎  
https://github.com/keboola/db-extractor-snowflake/issues/1

**Comment by ondrejhlavacek** [comment]
A znovu

https://connection.keboola.com/admin/utils/logs?file=2019/03/19/05/2019-03-19-05-20-17-5c906e010acbe-exception
https://connection.keboola.com/admin/utils/logs?file=2019/03/19/05/2019-03-19-05-20-17-5c906e0120753-log

**Comment by ondrejhlavacek** [comment]
a další https://keboola.slack.com/archives/C09U3R1J4/p1553088967015500

**Comment by ondrejhlavacek** [comment]
and again https://keboola.slack.com/archives/C09U3R1J4/p1553253128027200

**Comment by ondrejhlavacek** [comment]
aaaand again https://keboola.slack.com/archives/C09U3R1J4/p1553392990030100

**Comment by ondrejhlavacek** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1553499066031600

**Comment by ujovlado** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1553622547035100

**Comment by tomasfejfar** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1554378066006400 (a několik jiných od začátku týdne)

**Comment by ujovlado** [comment]
Presuvam do Jiry: https://keboola.atlassian.net/browse/COM-290
