### ISSUE TITLE
Object does not exist, or operation cannot be performed.

### ISSUE THREAD

**Issue by kacurez** [keboola/db-extractor-snowflake#83]
should be user error?
```
failed: (2) Snowsql error, process output 
* SnowSQL * v1.1.49 Type SQL statements or !help +----------------------------------+ | status                           | |----------------------------------| | Statement executed successfully. | +----------------------------------+ 1 Row(s) produced. Time Elapsed: 0.203s If the error message is not clear, enable the logging using -o log_level=DEBUG and see the log to find out the cause. Contact the support for further help. Goodbye! 
Snowsql error: 002043 (02000): SQL compilation error: Object does not exist, or operation cannot be performed. 
[2019-04-12 02:00:28] CRITICAL: Exception:File download error occurred processing [ads]
```

docker-86b893784365f0ecea009b7e2fa3a79f

**Comment by Halama** [comment]
Dnes opět https://keboola.slack.com/archives/C09U3R1J4/p1555891317020300

**Comment by Halama** [comment]
Zase https://keboola.slack.com/archives/C09U3R1J4/p1556150526046300

**Comment by Halama** [comment]
again https://keboola.slack.com/archives/C09U3R1J4/p1556236878053100

**Comment by odinuv** [comment]
me to dela furt kdyz extrahuju data z workspace (napojim extractor na writer workspace nebo transformacni workspace), prisahal bych, ze to driv slo a musit to byt neco z tema workspacama protoze to udela vzdycky a normalni ex jede

**Comment by odinuv** [comment]
failujici konfigurace https://connection.keboola.com/admin/projects/578/extractors/keboola.ex-db-snowflake/501288366

**Comment by ErikZigo** [comment]
@odinuv to je zvlastni ze ti to failuje vzdycky. Jak jsi to nakonfiguroval?

**Comment by odinuv** [comment]
vzal jsem credentials z workspacu writeru a zapsal jsem je tam :) tobe to nefailuje?

**Comment by ErikZigo** [comment]
Ja si u sebe zalozil writer s _Keboola provided database credentials_ a nahral tam tabulku.
Nakonfiguroval jsem si extractor a pouzil credentials z toho myho writeru.

A extractor mi beha normalne.
To same pokud zalozim tabulku v tom workspacu rucne ve snowflaku.

Si buildnu lokalne extractor a ukradnu ty tvoje failujici credentials a konfiguraci.

**Comment by odinuv** [comment]
strcil jsem tam https://connection.keboola.com/admin/projects/578/writers/keboola.wr-db-snowflake/501291625/credentials

klidne si hraj s tou konfiguraci https://connection.keboola.com/admin/projects/578/extractors/keboola.ex-db-snowflake/501288366 uz to na nic nepotrebuju

**Comment by ErikZigo** [comment]
V tvem pridade ten snowsql failne na query `USE SCHEMA "XY";`. Coz zatim teda nechapu.

**Comment by ErikZigo** [comment]
A dela mi to i u posledni verzne `snowsql`. To je zvlastni. To nechapu proc to nefailuje vsem ale jen tobe.

**Comment by ErikZigo** [comment]
Dela mi to i kdyz jsem zkusil updatnout drivery. Zkusim teda jeste na nejnovejsi. Ale bude to fakt nejaka divna haluz.

**Comment by odinuv** [comment]
no neuvedomuju si, ze bych delal nejakou haluz, vzal jsem proste credentials ze sandboxu strcil je tam, pak cvicne zkusil credentials z writeru a stejnej problem. nic vic jsem s tim myslim nedelal

**Comment by ErikZigo** [comment]
Ja zitra zkusim nejnovejsi ovladace a pak to asi zareportuju na snowflake i s debug dumpem ze snowsql.

**Comment by odinuv** [comment]
https://keboola.atlassian.net/browse/COM-102
